---

- name: Playbook for DB hosts
  hosts: db
  become: yes
  gather_facts: no
  roles:
    - db

# Play for app hosts, applying the 'app' role
- name: Playbook for app hosts
  hosts: app
  become: yes
  gather_facts: no
  roles:
    - app
